version: '3.0'
services:
  ovh-dns:
    build: .
    container_name: 'ovh_dns'
    stop_grace_period: '1s'
    restart: always
    environment:
      - APP_KEY=${APP_KEY}
      - APP_SECRET=${APP_SECRET}
      - APP_CONSUMER_KEY=${APP_CONSUMER_KEY}
      - ZONE_DNS=${ZONE_DNS}
      - SUB_DOMAIN=${SUB_DOMAIN}
      - CRON_SCHEDULE=${CRON_SCHEDULE}


